kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t flask-template .

- name: run
  commands:
    - cd /var/docker/flask-template
    - docker-compose stop flask-template flask-template-worker
    - docker-compose up -d flask-template flask-template-worker